version: "3.8"

services:
  frontend:
    build: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_URI=http://backend:8080/api

  backend:
    build: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/src
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
